[package]
name = "h"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = { version = "2.2.0", default-features = false }
radsort = "0.1.1"
typeid = "1.0.2"
wyhash = "0.5.0"

[features]
default = ["std"]
std = []

[profile.test]
opt-level = 3

[dev-dependencies]
zstd = "0.13.2"
