[package]
name = "h-test"
version = "0.1.0"
edition = "2021"

[dependencies]
h = { path = "../h" }

[build-dependencies]
h = { path = "../h", features = ["build", "codegen"] }
zstd = "0.13.2"

[features]
enabled = []

[lints]
workspace = true
